# Generated by Django 5.1.2 on 2024-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('side_effects', models.TextField()),
                ('dosage', models.TextField()),
                ('precautions', models.TextField()),
                ('interactions', models.TextField()),
                ('contraindications', models.TextField()),
                ('warnings', models.TextField()),
            ],
        ),
    ]
