# Generated by Django 5.1.2 on 2024-10-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsplain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
